import { Claim, ClaimStatus } from '@/types/schema';

// Mock claims data
export const mockClaims: Claim[] = [
  {
    id: 1,
    patient_id: 'P1',
    patient_name: 'John Smith',
    billing_code: 'B1001',
    amount: 1675.5,
    insurance_provider: 'Blue Shield',
    payment_status: ClaimStatus.Pending,
    claim_date: new Date('2025-03-25'),
  },
  {
    id: 2,
    patient_id: 'P2',
    patient_name: 'Sarah Johnson',
    billing_code: 'B2002',
    amount: 2310.09,
    insurance_provider: 'Medicare',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-01-05'),
  },

  {
    id: 3,
    patient_id: 'P3',
    patient_name: 'Robert Chen',
    billing_code: 'B3003',
    amount: 4945.57,
    insurance_provider: 'Aetna',
    payment_status: ClaimStatus.Pending,
    claim_date: new Date('2025-03-04'),
  },
  {
    id: 4,
    patient_id: 'P4',
    patient_name: 'Lisa Williams',
    billing_code: 'B4004',
    amount: 8338.89,
    insurance_provider: 'UnitedHealth',
    payment_status: ClaimStatus.Denied,
    claim_date: new Date('2025-03-20'),
  },
  {
    id: 5,
    patient_id: 'P5',
    patient_name: 'Michael Garcia',
    billing_code: 'B5005',
    amount: 3220.05,
    insurance_provider: 'Cigna',
    payment_status: ClaimStatus.Denied,
    claim_date: new Date('2025-02-21'),
  },
  {
    id: 6,
    patient_id: 'P6',
    patient_name: 'Emily Johnson',
    billing_code: 'B5006',
    amount: 1875.0,
    insurance_provider: 'UnitedHealthcare',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-03-02'),
  },
  {
    id: 7,
    patient_id: 'P7',
    patient_name: 'David Lee',
    billing_code: 'B5007',
    amount: 2450.75,
    insurance_provider: 'Blue Cross Blue Shield',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-01-15'),
  },
  {
    id: 8,
    patient_id: 'P8',
    patient_name: 'Sophia Martinez',
    billing_code: 'B5008',
    amount: 3999.99,
    insurance_provider: 'Aetna',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-04-05'),
  },
  {
    id: 9,
    patient_id: 'P9',
    patient_name: 'James Anderson',
    billing_code: 'B5009',
    amount: 1275.5,
    insurance_provider: 'Humana',
    payment_status: ClaimStatus.Pending,
    claim_date: new Date('2025-03-18'),
  },
  {
    id: 10,
    patient_id: 'P10',
    patient_name: 'Olivia Thomas',
    billing_code: 'B5010',
    amount: 3120.0,
    insurance_provider: 'Cigna',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-02-10'),
  },
  {
    id: 11,
    patient_id: 'P11',
    patient_name: 'William Rodriguez',
    billing_code: 'B5011',
    amount: 2150.25,
    insurance_provider: 'Kaiser Permanente',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-01-28'),
  },
  {
    id: 12,
    patient_id: 'P12',
    patient_name: 'Isabella Wilson',
    billing_code: 'B5012',
    amount: 1820.4,
    insurance_provider: 'UnitedHealthcare',
    payment_status: ClaimStatus.Denied,
    claim_date: new Date('2025-03-22'),
  },
  {
    id: 13,
    patient_id: 'P13',
    patient_name: 'Liam Nguyen',
    billing_code: 'B5013',
    amount: 2755.6,
    insurance_provider: 'Blue Cross Blue Shield',
    payment_status: ClaimStatus.Pending,
    claim_date: new Date('2025-02-28'),
  },
  {
    id: 14,
    patient_id: 'P14',
    patient_name: 'Mia Hernandez',
    billing_code: 'B5014',
    amount: 3410.95,
    insurance_provider: 'Aetna',
    payment_status: ClaimStatus.Approved,
    claim_date: new Date('2025-04-12'),
  },
  {
    id: 15,
    patient_id: 'P15',
    patient_name: 'Noah Scott',
    billing_code: 'B5015',
    amount: 2999.99,
    insurance_provider: 'Humana',
    payment_status: ClaimStatus.Denied,
    claim_date: new Date('2025-03-05'),
  },
];
